config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [ :index, :show, :edit, :update]
  resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root to: 'homes#top'
  get 'home/about', to: "homes#about", as: 'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   has_one_attached :image
   has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
   belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
    def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

    def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
   redirect_to request.referer
   end

  def destroy
      BookComment.find(params[:id]).destroy
      redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new

  end

def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
      # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)

  else
     @books = Book.all
   render :index
 end
end



  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
       user = @book.user
  unless user.id == current_user.id
    redirect_to books_path
  end
  end

  def update
    @book = Book.find(params[:id])
    user = @book.user
  unless user.id == current_user.id
    redirect_to books_path
  end
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
      user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end
     @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end

      @user = User.find(params[:id])
      if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
      else
       render :edit
      end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %>
   <h3>name <%= user.name %></h3>
   <h3>introduction	 <%= user.introduction	 %></h3>
       <%= link_to edit_user_path(user)  do %>
       <i class="fa-solid fa-user-gear">edit</i>
       <% end %>


<!-- 投稿フォーム -->
  <h1>New book</h1>
  <%= form_with model: book do |f| %>
    <h4>title</h4>
    <%= f.text_field :title %>
    <h4>説明</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li>error:<%= message %></li>
    <% end %>
      </ul>
<% end %>
<h2>Editing Book</h2>
<%= form_with model: @book do |f| %>
  <p></p><label for="Title">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:"名前"%>
  </p>

  <p><label for="Body">Opinion</label>
  <%= f.text_field :body, autofocus: true, id:"inputName", placeholder:"名前"%>
</p>
  <%= f.submit "Update Book" %>
<% end %>
        <%= link_to "Show", book_path(@book.id)%>
        <%= link_to "Back", books_path%>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= render 'list', book: @book, user: User.find(current_user.id) %>
  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <th>Title</th>
      <th>Opinion</th>
  <% @books.each do |post_image| %>
   <div class="row mb-3">
    <div class="col-md-3">
       <%= link_to user_path(post_image.user.id) do %>
     <p><%= image_tag post_image.user.get_profile_image(100,100) %></p>
      <% end %>
     </div>
  <div class="col-md-3">
    <%= link_to book_path(post_image.id) do %>
      <p><%= post_image.title %></p>
    <% end %>
      </div>
    <div class="col-md-3">
      <p><%= post_image.body%></p>
     </div>

     <% if post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorite_path(post_image), method: :delete do %>
      <i class="fa-solid fa-heart"></i><%= post_image.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorite_path(post_image), method: :post do %>
        <i class="fa-regular fa-heart"></i>
        <%= post_image.favorites.count %>
      <% end %>
    </p>
    <% end %>
      <div class="col-md-3">
            <p><%= link_to "#{post_image.book_comments.count} コメント",book_path(post_image.id) %></p>
      </div>
  </div>

  <% end %>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
<%= render 'list', book: @newbook, user: @book.user%>
  <div class="col-md-8 offset-md-1">
<h1>Book detail</h1>

  <div class="row mb-3">

  <div class="col-md-3">

   <%= link_to user_path(@book.user.id) do %>
     <%= image_tag @book.user.get_profile_image(100,100) %>
      <% end %>

    <%= link_to book_path(@book.id) do %>
      <%= @book.title %>
    <% end %>
    </div>
  <div class="col-md-2">
    <%= @book.body %>
  </div>

<div class="col-md-2">
  <%= link_to user_path(@book.user.id) do %>
    <%= @book.user.name %>
   <% end %>
    </div>
  <div class="col-md-2">
    <% if @book.user == current_user %>
      <%= link_to "Edit", edit_book_path(@book) %>
      <%= link_to "Destroy", book_path(@book), method: :delete %>
  </div>
      <% end %>

         <% if @book.favorited_by?(current_user) %>

            <%= link_to book_favorite_path(@book), method: :delete do %>
                    <i class="fa-solid fa-heart"></i>
              <%= @book.favorites.count %>
            <% end %>


          <% else %>

        <%= link_to book_favorite_path(@book), method: :post do %>
        <i class="fa-regular fa-heart"></i>
          <%= @book.favorites.count %>
        <% end %>

              </div>

  <% end %>

  </div>
  <div>
  <p>コメント件数：<%= @book.book_comments.count %></p>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>
    <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
     <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信" %>
  <% end %>
</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to  <i class="fa-solid fa-book"></i> Bookers!</h1>

app/views/homes/top.html.erb
<h1>welcome to
  <i class="fa-solid fa-book"></i>
Bookers !!</h1>
<p>In Bookers,</p>

<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>

     <p>
        <%= link_to "Log in", new_user_session_path %>
      </p>
      <p>
        <%= link_to "Sign up", new_user_registration_path %>
      </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <script src="https://kit.fontawesome.com/ffdbaf54a5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
         <%= link_to "Bookers",root_path %>

    <% if user_signed_in? %>

        <%= link_to user_path(current_user.id)  do %>
          <i class="fa-solid fa-house">Home</i>
          <% end %>



        <%= link_to  users_path do %>
         <i class="fa-solid fa-users">Users</i>
          <% end %>




        <%= link_to books_path do%>
            <i class="fa-solid fa-book-open">Books</i>
          <% end %>




        <%= link_to  destroy_user_session_path, method: :delete do %>
        <i class="fa-solid fa-right-from-bracket">Log out</i>
         <% end %>

    <% else %>

        <%= link_to root_path do  %>
          <i class="fa-solid fa-house">Home</i>
        <% end %>


        <%= link_to about_path do %>
          <i class="fa-solid fa-link">About</i>
        <% end %>


        <%= link_to new_user_registration_path do %>

          <i class="fa-solid fa-user-plus">Sign up</i>
        <% end %>


        <%= link_to new_user_session_path do %>
          <i class=" fa-solid fa-right-to-bracket">Log in</i>
        <% end %>

    <% end %>
  </header>
  <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_list.html.erb
    <div class="col-md-3">
   <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %>
   <h3>name <%= user.name %></h3>
   <h3>introduction	 <%= user.introduction	 %></h3>
       <%= link_to edit_user_path(user)  do %>
       <i class="fa-solid fa-user-gear">edit</i>
       <% end %>





<!-- 投稿フォーム -->

      <h1>New book</h1>
<%= form_with model: book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>
   </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
<% end %>
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>

<p>
  <label for="Name">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
</p>
<p>
  <label for="Image">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </p>
  <p>
  <label for="Introduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputName"%>
  </p>
  <p>
  <%= f.submit "Update User" %>
  </p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<%= render 'list', book: @book, user: User.find(current_user.id) %>

 <div class="col-md-8 offset-md-1">
  <h1>Users</h1>

      <td>image</td>
      <td>name</td>

      <% @users.each do |user| %>
        <div class="row mb-3">
          <div class="col-md-3">
            <%= link_to user_path(user.id) do %>
              <%= image_tag user.get_profile_image(100,100) %>
            <% end %>
          </div>
          <div class="col-md-3">
            <p><%= user.name %></p>
          </div>
          <div class="col-md-3">
            <%= link_to 'Show', user_path(user.id) %>
          </div>
     </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', book: @book, user: @user %>
    </div>

    <!-- ユーザーの投稿一覧 -->
    <div class="col-md-8 offset-md-1">
      <% @books.each do |book| %>
        <div class="row mb-3">
          <div class="col-md-3">
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </div>
          <div class="col-md-2">
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </div>
          <div class="col-md-2">
            <%= book.body %>
          </div>
          <div class="col-md-2">
            <%= book.user.name %>
          </div>
          <div class="col-md-2">
            <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
          </div>
          <div class="col-md-1">
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorite_path(book), method: :delete do %>
               <i class="fa-solid fa-heart"></i>
                <%= book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorite_path(book), method: :post do %>
              <i class="fa-regular fa-heart"></i>
              
                <%= book.favorites.count %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>